### PR TITLE
Sponsorship related

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**
- [x]  Add Sponsor button at top
- [x] Add Partners under which put [Townscript logo](http://rubyconfindia.org/) 
- [x]  Add logo of Red Panthers Software Solutions under T-Shirt Sponsor

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
@IndianGuru  Please check http://www.deccanrubyconf.org/

**Comment by IndianGuru** [comment]
@prathamesh-sonpatki should we not mention Ticketing sponsor and T-Shirt sponsor as can eb seen here - [http://rubyconfindia.org/](http://rubyconfindia.org/) ?

**Comment by prathamesh-sonpatki** [comment]
@IndianGuru Sure. @ahmad19 can you check how we can add the text "Ticketing sponsor", "T-shirt sponsor" next to logos of Townscript and Red Panthers?

**Comment by IndianGuru** [comment]
They have this:

**Comment by ahmad19** [comment]
sure i'll look in to it.

**Comment by ahmad19** [comment]
@prathamesh-sonpatki @IndianGuru What do you say about this ?
screen shot 2015-04-28 at 12 16 44 am

Both the logos are in span6, as the list grows, we can make a grid of 3 in a row or something?

**Comment by prathamesh-sonpatki** [comment]
@ahmad19 Looks good to me. We have to update the CSS once more sponsors come anyways. Can you open PR

**Pull request merged**
